# Generated by Django 3.1.7 on 2022-04-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
