# Generated by Django 3.1.7 on 2022-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Professor')], default=('S', 'Student'), max_length=9),
        ),
    ]
