# Generated by Django 3.1.7 on 2022-04-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='b', max_length=16),
            preserve_default=False,
        ),
    ]
