# Generated by Django 3.1.7 on 2022-04-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username'),
        ('users', '0003_auto_20220423_2249'),
    ]

    operations = [
    ]
